apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-{{ include "chart.fullname" . }}
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-{{ include "chart.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 4 }}
        app: rollouts-{{ include "chart.fullname" . }}
    spec:
      containers:
      - name: rollouts-{{ include "chart.fullname" . }}
        image: narioinc89/nodejs-user-api
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m